name: CI Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Set outputs
      id: vars
      run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)" &&
           echo "::set-output name=version_tag::${GITHUB_REF#refs/*/}" &&
           echo "::set-output name=solution_name::WineBridge.sln"
    - name: Restore dependencies
      working-directory: src/
      run: dotnet restore ${{ steps.vars.outputs.solution_name }}

    - name: Publish 
      working-directory: src/WineBridge
      run: dotnet publish --no-restore -c Release --runtime win-x86 --self-contained true /p:FileVersion="${{ steps.vars.outputs.version_tag }}" /p:Version="${{ steps.vars.outputs.version_tag }}" /p:AssemblyVersion="${{ steps.vars.outputs.version_tag }}" --version-suffix "-${{ steps.vars.outputs.sha_short }}"

    - name: Compress Release
      run: tar cJvf  WineBridge-${{ steps.vars.outputs.sha_short }}.tar.xz src/WineBridge/bin/Release/net6.0/win-x86/publish/WineBridge.exe

    - name: Upload Release
      uses: actions/upload-artifact@v2
      with:
        name: Release
        path: WineBridge-${{ steps.vars.outputs.sha_short }}.tar.xz
